version: '3.2'
services:
  kotlin-text-duplicates:
    #image: openjdk:8
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: kotlin-text-duplicates-container
    volumes:
      - .:/repo
    working_dir: /repo
    command: bash -c ./docker-start.sh
    ports:
      - 8081:8080
